### ISSUE TITLE
DEPRECATION: Using `should` 

### ISSUE THREAD

**Issue by unsown** [jayzes/cucumber-api-steps#32]
DEPRECATION: Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /home/yuan/.rvm/gems/ruby-2.0.0-p598/gems/cucumber-api-steps-0.13/lib/cucumber/api_steps.rb:151:in `block in <top (required)>'.

**Comment by jayzes** [comment]
Yes, that's a good call. I'd happily accept a pull request for this change.
