### ISSUE TITLE
Add token and JWT authentication

### ISSUE THREAD

**Issue by zedtux** [jayzes/cucumber-api-steps#45]
As of now, if I'm not mistaking, the gem is only supporting authentication using Basic auth.

What about token based authentication (In the path or HTTP `Authorization` header) and Json Web Token (JWT http://jwt.io) ?

**Comment by glaszig** [comment]
basic and digest auth are supported through rack-test and they are part of the http standard.
for token-based auth, there's different approaches. some use rails' `Token token="..."` header value. some use `Bearer token="..."`. someone else may use an entirely different thing.

for that reason, i'd be reluctant adding steps for each of those to the gem. i mean, it's quite easy to do it yourself, e.g.:

```rb
Before '@api' do
  api_auth = ActionController::HttpAuthentication::Token.encode_credentials \
    Rails.application.secrets[:api][:token]
  page.driver.header "Authorization", api_auth
end
```

**Comment by zedtux** [comment]
Thank you @glaszig for your comment. Maybe an update on the documentation so that it's clear and easy?
